# Generated by Django 5.2.1 on 2025-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
    ]
