# Generated by Django 5.2.1 on 2025-08-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default='descripcion'),
            preserve_default=False,
        ),
    ]
